### ISSUE TITLE
IFU sky subtraction on VIMOS lens observations

### ISSUE THREAD

**Issue by nrnapolita** [nrnapolita/KIWI_LSST#10]

**Comment by KiaraSpin** [comment]
I sent VIMOS data on one of our "best candidate" to Oliver Czoske who is very expert in VIMOS data reduction. He does not use the standar pipeline, but a self-written routine. If he gets results of better quality with respect to the ones that I obtained, we might think of sharing the whole sample to try to get the redshift of the probable source! 
I did not get a reply yet.

**Comment by KiaraSpin** [comment]
![obj_kids_139 0_-1 5_fits_07_04_001361_rgb](https://user-images.githubusercontent.com/19711937/33829249-d2fcfa76-de6f-11e7-9e92-76b11c59381a.jpg)


This is a KiDS rgb image created by Fedor of the candidate: KiDS_001361

**Comment by KiaraSpin** [comment]
![vimos_fov_001361](https://user-images.githubusercontent.com/19711937/33829347-291abf74-de70-11e7-85ce-2f0b6df13bcf.jpg)

This is the VIMOS reduced FOV. The upper panels are a single exposure (not necessarily the same) 
Up, left panel from O.Czoske
Up, right from CS 
The lower panel shows the final, combined (3 images) FOV obtained by CS. 

It is clear that Oliver is reducing a different field. CS still has to investigate why.

**Comment by KiaraSpin** [comment]
New update from Oliver. 
He manage to see the lens now (no idea what he did wrong the first time).
He sent me a spectrum with a first attempt to subtract the sky, but honestly for the moment he does a worse job than I did :( 

[KIDS001361-lens_redshift.pdf](https://github.com/nrnapolita/KIWI_LSST/files/1562736/KIDS001361-lens_redshift.pdf)

**Comment by KiaraSpin** [comment]
Group Meeting 18/12 : still problems with sky. Both Oliver and Chiara are doing their best.

**Comment by KiaraSpin** [comment]
Group Meeting 15/01 
-> AI Chiara Send a spectrum of galaxy and of sky to Francesco

**Comment by KiaraSpin** [comment]
Chiara sent the spectra to Francesco on 17/01

**Comment by KiaraSpin** [comment]
AI Chiara -> Try to flux-calibrate the spectra to detect the sources in the continuum rather than in emission lines

**Comment by KiaraSpin** [comment]
GM 19/03 
AI Chiara: 
reduce the new OB
THIS IS HOWEVER LOW PRIORITY
