### ISSUE TITLE
prepare a report for the KiDS busy meeting on the galaxy/cluster science

### ISSUE THREAD

**Issue by nrnapolita** [nrnapolita/KIWI_LSST#13]

**Comment by KiaraSpin** [comment]
@mariorpd13 any news?

**Comment by mariorpd13** [comment]
Text on clusters sent to Nicola

**Comment by nrnapolita** [comment]
Report about the nonWL activities, including DR4, assembled and sent by email!
We want to show wht we need the 9-band stuff for and what we are working on.
@KiaraSpin:  please send me some imeges
@ctortora:  do we have an image to add for the last page?

**Comment by KiaraSpin** [comment]
We sent our report and it was very appreciated and published in their pages. 
@mariorpd13 SUMMARY of the BUSY WEEK meeting: 
- Observations are going quite fast and it is foreseen that KiDS will be "completed" in Spring 2019 (stop at 1200 sq.deg which is the area also covered by VIKING). 
- The DR4 (900 sq.deg) will be released to the collaboration in 1-2 months (as always man-power is the bottom neck for time-schedule)
- ESO requires the next release by July 2018 (1000 sq. deg.) at most.
- A change to the KiDS memorandum has been proposed: if a project has been proposed and started *after* the publication of the data, there is no need to include in the paper all the people that reduced the data. 
- A comment: most (if not all) people working on data are part of the lensing team. The reduction and prioritizing of the data is biased toward lensing. 
- KiDS-N has high priority already for DR4. 

Attention: Concerning the GAMA overlap, the KIDS450 does not completely overlap. There are regions where the overlap will come only for 900.

@nrnapolita notes that for the science we want to do KiDS450 9-bands catalog is already enough. We only need to understand if we have the *FINAL VERSION* of it. 
It looks like there have been only few, minor changes.
