### ISSUE TITLE
KiDS+VIKING DR4 catalog

### ISSUE THREAD

**Issue by KiaraSpin** [nrnapolita/KIWI_LSST#24]
The **9-bands catalog (KiDS+VIKING)** for DR4 is avalilable on thor

- 9-band photometry and BPZ photometric redshifts catalogues:
/data/KIDS-1000/ESO-DR4-photometry-catalogues/

- weak lensing catalogues:
/data/KIDS-1000/K1000-SHEAR-9bandPZ-CATALOGUES/

_Originally posted by @KiaraSpin in https://github.com/nrnapolita/KIWI_LSST/issues/7#issuecomment-429850996_

**Comment by KiaraSpin** [comment]
AI @nrnapolita : Contact Stefano Cavuoti to check what is the situation with the ML redshift.

**Comment by nrnapolita** [comment]
A short update 
1) the ML photo-z have been produced for 41M of galaxies, by Cavuoti et al.
2) @ctortora and me are training a student in Zhuhai to derive stellar population and classification for these 41M galaxies.
