### ISSUE TITLE
Lensing project: 2DPHOT on HST images

### ISSUE THREAD

**Issue by nrnapolita** [nrnapolita/KIWI_LSST#5]
Nivya and Angela download HST images and run 2DPHOT on

**Comment by KiaraSpin** [comment]
https://hla.stsci.edu 
Here you can search for RA and DEC:
https://hla.stsci.edu/hlaview.html

**Comment by nrnapolita** [comment]
Maurizio has provided a 8 orbit image of its own to  test 2DPHOT on.
First tetsts are failing, that might be because there is some set-up missing. NR will check with FLV today and report here below!

**Comment by nrnapolita** [comment]
CS: the proposal for Phase2 has deadline in two days. The APT proposal has been checked from Maurizio. There might be an issue on the observational strategy about the dithering strategy and the possibility of having a gap in the center. Maurizio will check the issue, CS also will check it more. 
Why don't we go with an offset anyway to be sure?

**Comment by KiaraSpin** [comment]
The proposal has been submitted and accepted already by the supporter astronomer... now finger crossed!

**Comment by nivyaaroy** [comment]
I did 2dphot run with new gain and saturation values. Attach here is a file with comparison between LSST input parameter and 2dphot output. The results are not good. Anyway as examples I add some output plots from 2dphot along with the source and residual fits stamps
[Uploading LSST_2dphot.pdf…]()

**Comment by KiaraSpin** [comment]
Group Meeting 18/12: Nyvia and Angela currently working on it. Still minor tecnical issues with the code. 
AI NRN: Check this further.

**Comment by KiaraSpin** [comment]
Group Meeting 15/01/2018
Nyvia and Angela are working on it. Something was not working before Christmas, but we are still not sure what the real issue is. 2DPHOT was not completing the run, it was stopping and not creating PSF. 
-> AI Francesco: follow up on this issue (ask Amata?) 

In theory we can simply use GALFIT for this purpose once Angela becomes an expert
-> AI Angela: learn how to use GALFIT

**Comment by KiaraSpin** [comment]
GM 29/01 
Check #4 
we will try to run GALFIT also on HST

**Comment by KiaraSpin** [comment]
GM 12/02
Angela has run 2DPHOT and GALFIT on the same galaxy. 
AI for @MariaAngelaRaj : 
1. Take one of the galaxy from Nyvia's paper. Update here the image, ps file with also residual map.
2. Report here the parameters from 2DPHOT that are used as input for GALFIT
3. Update here the results from GALFIT with possibly image too

**Comment by KiaraSpin** [comment]
GM 14/05 
Chiara will send the fits file to @MariaAngelaRaj who will try to model them.

**Comment by KiaraSpin** [comment]
@MariaAngelaRaj @ctortora  @nrnapolita you can download the FITS files from here:
https://drive.google.com/file/d/1IQ3xENTwRySEO1zoqTUewS4Wy6NXAdQk/view?usp=sharing
