### ISSUE TITLE
GAIN and SATURATE values in LSST DC1 simulated images

### ISSUE THREAD

**Issue by nrnapolita** [nrnapolita/KIWI_LSST#8]
Need to check the GAIN and SATURATE values in LSST DC1 simulated images in thor dir
/home/nnicola/LSST/NERSC

**Comment by nrnapolita** [comment]
AI: 
1) everybody try to find info about this online
2) NRN keep chasing LSST people to know that

**Comment by KiaraSpin** [comment]
GM 18/12: Nyvia got the right values and is trying to make a 1-to-1 comparison between 2DPHOT and LSST. See issue #4
